# Elektromagnetische Verträglichkeit (EMV)

::: callout-note
[Elektrische Ladungen]{.underline} eines [Wechselstroms]{.underline} ($\dot{I}$), also der Änderungsrate des Stromes, [erzeugen]{.underline} ein [elektromagnetische Feld]{.underline}. $\rightarrow$ Somit ist ein elektronisches System von vielen unterschiedlichen Quellen von Störungen und Rauschen ausgesetzt.
:::

Man unterscheidet diese Rauschquellen in drei Kategorie

1.  **Ausgesendetes Rauschen** -- welches zusammen mit dem Nutzsignal empfangen. Diese Störung kann **nicht** vom Nutzsignal unterschieden werden!
2.  **Intrinsisches Rauschen** -- Rauschen [innerhalb]{.underline} der Schaltung (z.B. thermisches Rauschen & Shot-Rauschen von Halbleitern)
3.  **Externe Störgeräusche** -- Werden vom System aufgefangen (z.B. entstehen durch Gewitterentladungen oder von anderen elektrischen Geräten)

| Art                                                                          | Herkunft                                                                                                      |
|---------------------------------------|---------------------------------|
| Schmalbandige Störsignale                                                    | z.B. Langwellen- und Mittelwellen-Radiosender                                                                 |
| Breitbandige Störsignale                                                     | Mobilfunksignale, Datenkommunikation mit hoher Datenrate (Übersprechen von benachbarten Übertragungssystemen) |
| Periodische, pulshafte Störsignale, [synchron]{.underline} zur Netzfrequenz  | Leistungselektronik in der Antriebssteuerung                                                                  |
| Periodische, pulshafte Störsignale, [asynchron]{.underline} zur Netzfrequenz | z.B. getaktete Netzteile; diskrete Spektrallinien von 50Hz...200Hz                                            |
| Nichtperiodisches, pulshaftes Rauschen                                       | z.B. Gewitterentladungen; Impulsdauer bis einige Millisekunden                                                |
| Farbiges Hintergrundrauschen                                                 | Verschiedene Quellen mit tiefer spektraler Leistungsdichte ; Zeitkonstante von Minuten bis Stunden            |
|                                                                              |                                                                                                               |

$$
T=\frac{1}{f}\qquad \lambda=\frac{v}{f}\qquad E=h\cdot f
$$

```{=latex}
\begin{conditions}
  T       & Periodendauer \\ 
  \lambda & Wellenlänge \\
  f       & Frequenz \\
  v       & Phasengeschwindigkeit \\
  E       & Photonenenergie ; mit der Frequenz übertragbare minimale Energie \\
  h       & Plank'sche Konstante $4.136\cdot 10^{-15} eVs$ \\
\end{conditions}
```
## Magnetische Feldenergie

$$
w_m = \frac12\cdot L\cdot i^2
$$

## Elektrische Feldenergie

$$
w_e = \frac12\cdot C\cdot u^2
$$