# Dynamik

## Lösen von Differential Gleichungen

::: callout-important
## Lösung einer Differentialgleichung

$$
x(t_0)=x_0\quad\frac{dx(t)}{dt}=F(x(t))
$$
:::

## Gleichgewichtslage

Eine Gleichgewichtslage ist ein Zustand in dem das System [stabil]{.underline} ist. Dies ist auch bekannt als *stationäres* Verhalten und weist [keine]{.underline} Veränderungen auf mit der Zeit.

$x_e$ ist eine Gleichgewichtslage des dynamischen Systems $\frac{dx}{dt}=F(x)$ falls:

$$
F(x_e)=0 \rightarrow \frac{dx}{dt}\biggr\rvert_{x_e}=0
$$

## Testfunktion Sprungantwort

Anhand folgender Funktion kann die Sprungantwort eines Systems angegeben werden.

$$
y(t)=Ce^{At}x(0)+\int^t_0Ce^{A(t-\tau)}Bu(\tau)d\tau+Du(t)
$$

Die Antwort setzt aus einem *zeitabhängigen* und einem *konstanten* Teil zusammen.

$$
y(t)=\underbrace{CA^{-1}e^{At}B}_{\text{zeitabhängig}}\underbrace{-CA^{-1}B+D}_{\text{konstant}}\qquad t>0
$$

Das System strebt gegen Wert wenn A [asymptotisch stabil]{.underline} ist $\rightarrow$ der *zeitabhängige* Teil strebt, falls A asymptotisch stabil ist, der Gleichtgewichtslage $x=0$ zu. Der *konstante* Teil entspricht dem Wert bei $\omega\rightarrow 0$ und damit der *Gleichspannungsverstärkung*.