project:
  type: chribel-summary-quarto
  output-dir: ".."
  render: 
    - s6_real-time_image_processing.qmd

format:
  chribel-summary-quarto-pdf:
    include-in-header:
    - text: "\\usepackage[datesep=.]{datetime2}"
    - text: "\\DTMsetdatestyle{ddmmyyyy}"
    toc: true
    classoption: twocolumn

# [DOCUMENT INFORMATION]
title: "Real-Time Image Processing"
subtitle: "Zusammenfassung"
author: "Joel von Rotz"

# [PAGE OPTIONS]
lang: de-CH
babel-lang: nswissgerman

# [HEADER & FOOTER]
fancyhdr:
  header:
    right: Real-Time Image Processing - Zusammenfassung
    center: ""
    left: "HSLU T&A"
  footer:
    right: "EBV"
    center: "\\thepage\\ / \\pageref{LastPage}"
    left: "\\DTMtoday"
  
source:
  github: "https://www.youtube.com/watch?v=VGhcSupkNs8"

accentcolor: "124E82" # must be given as hex, sadly :(

chribel-fontfamily:
  - name: AlegreyaSans      # used for section headings, title page
  - name: cmbright          # used for paragraph and math
  - name: inconsolata
    options: "scaled=0.95"  # for code blocks